volumes:
    data:
services:
    db:
        image: mariadb
        container_name: mousefinancebot-db
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_SCHEMA}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
        volumes:
            - ./data:/var/lib/mysql
        ports:
            - "${DATABASE_FORWARD:-3306}:3306"
