version: "3.8"
volumes:
  data:
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_SCHEMA}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_USER_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "${DATABASE_FORWARD:-3306}:3306"
    networks:
      - backend
    restart: always

  web:
    image: anoniemebeer/mousefinancebot:latest_main
    environment:
      CLIENT_TOKEN: ${CLIENT_TOKEN}
      GUILD_ID: ${GUILD_ID}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_SCHEMA: ${DATABASE_SCHEMA}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_USER_PASSWORD: ${DATABASE_USER_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - backend
    restart: always

networks:
  backend:
